import os
import json
import asyncio
import logging
from datetime import datetime
from paho.mqtt import client as mqtt_client
from google.antigravity import Agent, LocalAgentConfig, types

# Configure logging to display SDK and execution logs
logging.basicConfig(level=logging.INFO)

# ==============================================================================
# 1. CONFIGURATION & PATH RESOLUTION
# ==============================================================================
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

os.environ["GEMINI_API_KEY"] = "AIzaSyCQaUmUG74HEHD2AUCdVwOJdFp3lDrEfFs"

MQTT_BROKER_IP = "192.168.0.110"
MQTT_PORT = 1883
MQTT_TOPIC = "mace/telemetry/tradfi_shield"

ALPACA_API_KEY = "PKPQBCDBNXHU4XUXRDUB7AFIEF"
ALPACA_SECRET_KEY = "3GZDRF2b1fxKrmvNLp9ZdQRo6rceDw4KFve9W9kYS1R9"

PROMPT = (
    "You are M.A.C.E. TRADFI SHIELD, an autonomous risk-reflex agent.\n"
    "Your sole objective is to monitor and protect capital using the Alpaca MCP tools.\n\n"
    "EXPLICIT DIRECTIVES:\n"
    "1. Audit Positions: Call the `mcp_alpaca_get_all_positions` tool to fetch all currently held positions in your portfolio.\n"
    "2. Inspect Unrealized PnL: For each position returned, check the unrealized profit/loss percentage (represented as `unrealized_plpc` inside the position object).\n"
    "3. Trigger Safe Exit: If any position has an unrealized loss of 8% or worse (i.e. `unrealized_plpc` <= -0.08, which is -8%), execute an immediate liquidating exit by calling the `mcp_alpaca_close_position` tool with the `symbol` parameter set to the asset's ticker symbol.\n"
    "4. Summary: Return a clean, formatted JSON summary listing the assets inspected, their PnL percentages, any liquidation actions executed, or stating 'Portfolio stable' if no positions breached the stop-loss limit."
)

# ==============================================================================
# 2. THE RISK REFLEX LOOP
# ==============================================================================
async def run_shield():
    print("[*] Booting M.A.C.E. TRADFI SHIELD with Google Antigravity...")

    # Set Alpaca credentials in environment so the MCP server can inherit them
    os.environ["ALPACA_API_KEY"] = ALPACA_API_KEY
    os.environ["ALPACA_SECRET_KEY"] = ALPACA_SECRET_KEY
    os.environ["ALPACA_PAPER_TRADE"] = "true"

    uvx_cmd = "/usr/local/bin/uvx" if os.path.exists("/usr/local/bin/uvx") else "uvx"

    # Configure stdio MCP server for Alpaca using env wrapper to guarantee key propagation
    mcp_servers = [
        types.McpStdioServer(
            name="alpaca",
            command="/usr/bin/env",
            args=[
                f"ALPACA_API_KEY={ALPACA_API_KEY}",
                f"ALPACA_SECRET_KEY={ALPACA_SECRET_KEY}",
                "ALPACA_PAPER_TRADE=true",
                uvx_cmd,
                "alpaca-mcp-server",
            ],
        )
    ]

    config = LocalAgentConfig(
        model="gemini-2.5-flash",  # High-frequency speed/reflex model
        system_instructions=PROMPT,
        mcp_servers=mcp_servers,
    )

    print("[*] Handing control to Google Antigravity Agent (Gemini 2.5 Flash)...")

    async with Agent(config=config) as agent:
        # Robust Retry Loop for API Demand Spikes
        max_retries = 3
        retry_delay = 5  # seconds
        response = None

        for attempt in range(max_retries):
            try:
                response = await agent.chat("Execute the TradFi risk reflex audit.")
                break  # Success!
            except Exception as e:
                if ("503" in str(e) or "429" in str(e)) and attempt < max_retries - 1:
                    print(f"[!] Gemini busy ({e}). Retrying in {retry_delay}s... (Attempt {attempt + 1}/{max_retries})")
                    await asyncio.sleep(retry_delay)
                    retry_delay *= 2  # Exponential backoff
                else:
                    raise e  # Critical error or final attempt failed, bubble it up

        if response:
            try:
                text_content = await response.text()
                if text_content and text_content.strip():
                    return text_content
            except Exception as e:
                print(f"[!] Error retrieving response text: {e}")
            
            # Safe fallback if text is empty/unreadable but tools ran successfully
            return json.dumps({"status": "Success", "details": "Alpaca MCP stop-loss audit completed successfully."})
        else:
            return json.dumps({"error": "No response generated by risk agent."})

def push_telemetry(result):
    print(f"\n=== TRADFI SHIELD REPORT ===\n{result}\n============================\n")
    try:
        mqttc = mqtt_client.Client(mqtt_client.CallbackAPIVersion.VERSION2)
        
        # Support secure credentials for Home Assistant / local secure brokers
        user = os.environ.get("MQTT_USER")
        password = os.environ.get("MQTT_PASSWORD")
        if user and password:
            mqttc.username_pw_set(user, password)
            
        mqttc.connect(MQTT_BROKER_IP, MQTT_PORT, 10)
        mqttc.loop_start()
        
        # Publish and wait for completion (timeout after 5 seconds to prevent blocking)
        payload = {"timestamp": str(datetime.now()), "engine": "TRADFI_SHIELD", "report": result}
        info = mqttc.publish(MQTT_TOPIC, json.dumps(payload))
        info.wait_for_publish(timeout=5)
        
        mqttc.loop_stop()
        mqttc.disconnect()
        print("[+] Telemetry published successfully via MQTT.")
    except Exception as e:
        print(f"[!] MQTT Failed: {e}")

import argparse

async def main():
    parser = argparse.ArgumentParser(description="M.A.C.E. TradFi Shield Stop-Loss Monitor")
    parser.add_argument("--daemon", action="store_true", help="Run continuously in background daemon mode")
    parser.add_argument("--interval", type=int, default=900, help="Interval between audits in seconds in daemon mode (default: 900s / 15m)")
    args = parser.parse_args()

    if args.daemon:
        print(f"[*] Starting M.A.C.E. TradFi Shield in DAEMON mode (interval: {args.interval}s)...")
        while True:
            try:
                result = await run_shield()
                push_telemetry(result)
            except Exception as e:
                print(f"[!] Error in Shield daemon audit cycle: {e}")
            print(f"[*] Sleeping for {args.interval} seconds before next risk audit...")
            await asyncio.sleep(args.interval)
    else:
        result = await run_shield()
        push_telemetry(result)

if __name__ == "__main__":
    asyncio.run(main())
