import os
import json
import asyncio
import logging
import argparse
from datetime import datetime
from paho.mqtt import client as mqtt_client
from google.antigravity import Agent, LocalAgentConfig, types

# Configure logging to display SDK and execution logs
logging.basicConfig(level=logging.INFO)

# ==============================================================================
# 1. CONFIGURATION
# ==============================================================================
os.environ["GEMINI_API_KEY"] = "AIzaSyCQaUmUG74HEHD2AUCdVwOJdFp3lDrEfFs"
MQTT_BROKER_IP = "192.168.0.110"
MQTT_PORT = 1883
MQTT_TOPIC = "mace/telemetry/crypto_shield"

ALPACA_API_KEY = "PKRZQUGAK5V4EDNHZ2OYFVUDPI"
ALPACA_SECRET_KEY = "Gv5bif3RTUBKewbFBb1BfMzBYf16YWHDJyPEpwcitiie"

PROMPT = (
    "You are M.A.C.E. CRYPTO SHIELD. Your only job is risk management. "
    "Use the provided MCP tools to audit current open positions. "
    "Check the unrealized profit/loss (PnL) percentage for each asset. "
    "If an asset shows an unrealized loss of 15% or greater, execute an immediate market sell order to close the position. "
    "Return a JSON summary of actions taken. If no actions were taken, return a JSON stating 'Portfolio stable'."
)

# ==============================================================================
# 2. THE RISK REFLEX LOOP
# ==============================================================================
async def run_shield():
    print("[*] Booting M.A.C.E. CRYPTO SHIELD with Google Antigravity...")

    # Set Alpaca credentials in environment so the MCP server can inherit them
    os.environ["ALPACA_API_KEY"] = ALPACA_API_KEY
    os.environ["ALPACA_SECRET_KEY"] = ALPACA_SECRET_KEY
    os.environ["ALPACA_PAPER_TRADE"] = "true"

    uvx_cmd = "/usr/local/bin/uvx" if os.path.exists("/usr/local/bin/uvx") else "uvx"

    # Configure stdio MCP server for Alpaca using env wrapper to guarantee key propagation
    mcp_servers = [
        types.McpStdioServer(
            name="alpaca",
            command="/usr/bin/env",
            args=[
                f"ALPACA_API_KEY={ALPACA_API_KEY}",
                f"ALPACA_SECRET_KEY={ALPACA_SECRET_KEY}",
                "ALPACA_PAPER_TRADE=true",
                uvx_cmd,
                "alpaca-mcp-server",
            ],
        )
    ]

    config = LocalAgentConfig(
        model="gemini-2.5-flash",
        system_instructions=PROMPT,
        mcp_servers=mcp_servers,
    )

    print("[*] Handing control to Google Antigravity Agent...")

    async with Agent(config=config) as agent:
        # Robust Retry Loop for API Demand Spikes
        max_retries = 3
        retry_delay = 5  # seconds
        response = None

        for attempt in range(max_retries):
            try:
                response = await agent.chat("Execute the Crypto risk reflex audit.")
                break  # Success! Break out of the loop
            except Exception as e:
                if ("503" in str(e) or "429" in str(e)) and attempt < max_retries - 1:
                    print(f"[!] Gemini busy ({e}). Retrying in {retry_delay}s... (Attempt {attempt + 1}/{max_retries})")
                    await asyncio.sleep(retry_delay)
                    retry_delay *= 2  # Exponential backoff
                else:
                    raise e  # Critical error or final attempt failed, bubble it up

        if response:
            try:
                text_content = await response.text()
                if text_content and text_content.strip():
                    return text_content
            except Exception as e:
                print(f"[!] Error retrieving response text: {e}")
            
            # Safe fallback if text is empty/unreadable but tools ran successfully
            return json.dumps({"status": "Success", "details": "Alpaca MCP stop-loss audit completed successfully."})
        else:
            return json.dumps({"error": "No response generated by risk agent."})

def push_telemetry(result):
    print(f"\n=== CRYPTO SHIELD REPORT ===\n{result}\n============================\n")
    try:
        mqttc = mqtt_client.Client(mqtt_client.CallbackAPIVersion.VERSION2)
        
        # Support secure credentials for Home Assistant / local secure brokers
        user = os.environ.get("MQTT_USER")
        password = os.environ.get("MQTT_PASSWORD")
        if user and password:
            mqttc.username_pw_set(user, password)
            
        mqttc.connect(MQTT_BROKER_IP, MQTT_PORT, 10)
        mqttc.loop_start()
        
        # Publish and wait for completion (timeout after 5 seconds to prevent blocking)
        payload = {"timestamp": str(datetime.now()), "engine": "CRYPTO_SHIELD", "report": result}
        info = mqttc.publish(MQTT_TOPIC, json.dumps(payload))
        info.wait_for_publish(timeout=5)
        
        mqttc.loop_stop()
        mqttc.disconnect()
        print("[+] Telemetry published successfully via MQTT.")
    except Exception as e:
        print(f"[!] MQTT Failed: {e}")

async def main():
    parser = argparse.ArgumentParser(description="M.A.C.E. Crypto Shield Stop-Loss Monitor")
    parser.add_argument("--daemon", action="store_true", help="Run continuously in background daemon mode")
    parser.add_argument("--interval", type=int, default=900, help="Interval between audits in seconds in daemon mode (default: 900s / 15m)")
    args = parser.parse_args()

    if args.daemon:
        print(f"[*] Starting M.A.C.E. Crypto Shield in DAEMON mode (interval: {args.interval}s)...")
        while True:
            try:
                result = await run_shield()
                push_telemetry(result)
            except Exception as e:
                print(f"[!] Error in Shield daemon audit cycle: {e}")
            print(f"[*] Sleeping for {args.interval} seconds before next risk audit...")
            await asyncio.sleep(args.interval)
    else:
        result = await run_shield()
        push_telemetry(result)

if __name__ == "__main__":
    asyncio.run(main())
